name: PR Checks Passed
on:
  workflow_run:
    workflows: ["C/C++ CI", "Check Documentation"]
    types:
      - completed

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    steps:
      - echo "Either the C/C++ CI or Check Documentation workflow must pass."
      - exit 1
